using System.Collections.Generic;
using MTG.DataExtractor.Objects.Managers;

namespace MTG.DataExtractor.Objects
{
	public class DonneeCarte
	{

		public enum TYPE_DONNEE
		{
			CARD_NAME,
            CARD_NAMES,
            CARD_FOREIGN_NAME,
			CARD_FOREIGN_NAME_CHINESE_TRADITIONAL,
			CARD_FOREIGN_NAME_CHINESE_SIMPLIFIED,
			CARD_FOREIGN_NAME_FRENCH,
			CARD_FOREIGN_NAME_GERMAN,
			CARD_FOREIGN_NAME_ITALIAN,
			CARD_FOREIGN_NAME_JAPANESE,
			CARD_FOREIGN_NAME_KOREAN,
			CARD_FOREIGN_NAME_PORTUGUESE,
			CARD_FOREIGN_NAME_PORTUGUESE_BRAZIL,
			CARD_FOREIGN_NAME_RUSSIAN,
			CARD_FOREIGN_NAME_SPANISH,
			CARD_MUTIVERSEID,
			CARD_VARIATIONS,
			CARD_LAYOUT,
			CARD_TYPE,
			CARD_ORIGINAL_TYPE,
			CARD_TYPES,
			CARD_SUBTYPES,
			CARD_SUPERTYPES,
			CARD_COLORS,
			CARD_CMC,
			CARD_MANACOST,
			CARD_RARITY,
			CARD_POWER,
			CARD_TOUGHNESS,
			CARD_LOYALTY,
			CARD_TEXT,
			CARD_ORIGINAL_TEXT,
			CARD_ARTIST,
			CARD_FLAVOR,
			CARD_IMAGENAME,
			CARD_NUMBER,
			CARD_WATERMARK,
			CARD_BORDER,
			CARD_HAND,
            CARD_LIFE,
            CARD_LEGALITY,
            CARD_LEGALITY_STANDARD,
			CARD_LEGALITY_MODERN,
			CARD_LEGALITY_LEGACY,
			CARD_LEGALITY_VINTAGE,
			CARD_LEGALITY_FREEFORM,
			CARD_LEGALITY_PRISMATIC,
			CARD_LEGALITY_TRIBAL_WARS_LEGACY,
			CARD_LEGALITY_TRIBAL_WARS_STANDARD,
			CARD_LEGALITY_SINGLETON_100,
			CARD_LEGALITY_COMMANDER,
			CARD_PRINTINGS,
			CARD_RULINGS
		}

        public TYPE_DONNEE TypeDonnee;

        public override string ToString()
		{
			return ManageDonneeCarte.Libelle(this);
		}

		public DonneeCarte(TYPE_DONNEE typeDonnee)
		{
			TypeDonnee = typeDonnee;
		}

    }
}
