#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UI.MtgLifeCounter.Android.Resource", IsApplication=true)]

namespace UI.MtgLifeCounter.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Business.MtgLifeCounter.Resource.String.ApplicationName = global::UI.MtgLifeCounter.Android.Resource.String.ApplicationName;
			global::Business.MtgLifeCounter.Resource.String.Hello = global::UI.MtgLifeCounter.Android.Resource.String.Hello;
			global::Common.Android.Resource.String.ApplicationName = global::UI.MtgLifeCounter.Android.Resource.String.ApplicationName;
			global::Common.Android.Resource.String.Hello = global::UI.MtgLifeCounter.Android.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int change_score_inverse_life = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int change_score_life = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cycle_life = 2131034114;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int transparent = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int application = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int down_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menu_about = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu_close = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_debug = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu_dice = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menu_help = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_history = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_rate = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menu_reload = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menu_rules = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menu_search = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menu_settings = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int up_arrow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int wallpaper_opponent = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int wallpaper_player = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int btnImgExpander = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int frame_container = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int frame_main = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int ivMenuImg = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int menuIconImgView = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int menuListView = 2131296263;
			
			// aapt resource value: 0x7f090001
			public const int titleBarLinearLayout = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int txtActionBarText = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int txtDescription = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int txtMnuText = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Activity_Intro = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Activity_Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Fragment_About = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Fragment_Debug = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Fragment_Dice = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Fragment_Help = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Fragment_History = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Fragment_Menu_Item = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Fragment_Rate = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Fragment_Reload = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Fragment_Rules = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Fragment_Search = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Fragment_Settings = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int AboutUs = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int Clients = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int ContactUs = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int Events = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int Help = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int Home = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Products = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int Service = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int Solution = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int hello = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int menu_about = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int menu_close = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int menu_debug = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int menu_dice = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int menu_help = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int menu_main = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int menu_rate = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int menu_reload = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int menu_rules = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int menu_search = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int menu_settings = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
