#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UI.MtgLifeCounter.Android.Resource", IsApplication=true)]

namespace UI.MtgLifeCounter.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Business.MtgLifeCounter.Resource.String.ApplicationName = global::UI.MtgLifeCounter.Android.Resource.String.ApplicationName;
			global::Business.MtgLifeCounter.Resource.String.Hello = global::UI.MtgLifeCounter.Android.Resource.String.Hello;
			global::Common.Android.Resource.String.ApplicationName = global::UI.MtgLifeCounter.Android.Resource.String.ApplicationName;
			global::Common.Android.Resource.String.Hello = global::UI.MtgLifeCounter.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int transparent = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int down_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menu_about = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menu_close = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu_debug = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_dice = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu_help = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menu_history = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_rate = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_reload = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menu_rules = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menu_search = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menu_settings = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int up_arrow = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int btnImgExpander = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int frame_container = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int ivMenuImg = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int menuIconImgView = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int menuListView = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int myButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int titleBarLinearLayout = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int txtActionBarText = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int txtActionBarText2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int txtActionBarText3 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int txtDescription = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int txtMnuText = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Activity_Intro = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Activity_Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Fragment_About = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Fragment_Debug = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Fragment_Dice = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Fragment_Help = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Fragment_History = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Fragment_Menu_Item = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Fragment_Rate = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Fragment_Reload = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Fragment_Rules = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Fragment_Search = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Fragment_Settings = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int AboutUs = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int Clients = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int ContactUs = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int Events = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int Help = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int Home = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int Products = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int Service = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int Solution = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int menu_about = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int menu_close = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int menu_debug = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int menu_dice = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int menu_help = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int menu_history = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int menu_rate = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int menu_reload = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int menu_rules = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int menu_search = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int menu_settings = 2131034135;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
