namespace DataBase.Bestiaire.Enumerations
{
    public class Enums
	{

		public enum COLUMNS_DRAFTS
		{
			DATABASE_ID,
			ID,
			NAME,
			EDITION_1,
			EDITION_2,
			EDITION_3,
			HIGHLANDER
		}

		public enum COLUMNS_EDITIONS
		{
            DATABASE_ID,
			ID,
			NAME,
			PREMIUMS,
			TRICOLORS,
			MYTHICS,
			LANDS,
			TRANSFORMS,
			NB_MYTHICS,
			NB_RARES,
			NB_UNCOS,
			NB_COMMUNES,
			NB_RARES_SPECIALES,
			NB_UNCOS_SPECIALES,
			NB_COMMUNES_SPECIALES,
			DATA_GATHERER_LOADED,
			DATA_BESTIAIRE_LOADED,
			DATA_IMAGES_LOADED
		}

		public enum COLUMNS_CARDS
		{
            DATABASE_ID,
			ID,
			EDITION_ID,
			NAME,
			COLOR,
			RARITY,
			CMC,
			ACTIF,
			TRANSFORM,
			TYPE,
			NOTES,
			PICKS,
			GATHERER_NAME,
			GATHERER_MULTIVERSE_ID,
			GATHERER_TYPE,
			GATHERER_TYPES,
			GATHERER_SUBTYPES,
			GATHERER_SUPERTYPES,
			GATHERER_COLORS,
			GATHERER_CMC,
			GATHERER_MANA_COST,
			GATHERER_RARITY,
			GATHERER_POWER,
			GATHERER_TOUGHNESS,
			GATHERER_LOYALTY,
			GATHERER_TEXT,
			GATHERER_IMAGE_NAME,
			GATHERER_NUMBER
		}

	}
}

