#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UI.DraftBestiaire.Android.Resource", IsApplication=true)]

namespace UI.DraftBestiaire.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Business.Resources.Resource.String.ApplicationName = global::UI.DraftBestiaire.Android.Resource.String.ApplicationName;
			global::Business.Resources.Resource.String.Hello = global::UI.DraftBestiaire.Android.Resource.String.Hello;
			global::Business.Resources.Resource.String.library_name = global::UI.DraftBestiaire.Android.Resource.String.library_name;
			global::Common.Android.Resource.String.ApplicationName = global::UI.DraftBestiaire.Android.Resource.String.ApplicationName;
			global::Common.Android.Resource.String.Hello = global::UI.DraftBestiaire.Android.Resource.String.Hello;
			global::Common.AsyncTasks.Resource.String.ApplicationName = global::UI.DraftBestiaire.Android.Resource.String.ApplicationName;
			global::Common.AsyncTasks.Resource.String.Hello = global::UI.DraftBestiaire.Android.Resource.String.Hello;
			global::Common.AsyncTasks.Resource.String.library_name = global::UI.DraftBestiaire.Android.Resource.String.library_name;
			global::Objects.Bestiaire.Resource.String.library_name = global::UI.DraftBestiaire.Android.Resource.String.library_name;
			global::Objects.MtgJson.Resource.String.library_name = global::UI.DraftBestiaire.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int down_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menu_about = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menu_close = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu_dci = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_debug = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu_home = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menu_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_ranking = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_search = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_settings = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int up_arrow = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnImgExpander = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int draftEditionCode1 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int draftEditionCode2 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int draftEditionCode3 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int draftName = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int editionID = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int editionName = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int frame_container = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int ivMenuImg = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int menuIconImgView = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int menuListView = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int spinnerDrafts = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int spinnerEditions1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int spinnerEditions2 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int spinnerEditions3 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int titleBarLinearLayout = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int tvDebug = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int txtActionBarText = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int txtDescription = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int txtMnuText = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Activity_Intro = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Activity_Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Fragment_About = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Fragment_Debug = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Fragment_DisplayEdition = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Fragment_Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Fragment_Menu_Item = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Fragment_PlaneswalkerPoints = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Fragment_Ranking = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Fragment_Settings = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Spinner_Drafts = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Spinner_Drafts_Selection = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Spinner_Editions = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Spinner_Editions_Selection = 2130968589;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int AboutUs = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int Clients = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int ContactUs = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int Events = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int Help = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Home = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int Products = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int Service = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int Solution = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int menu_about = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int menu_close = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int menu_debug = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int menu_display_edition = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int menu_planeswalker_points = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int menu_play_draft = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int menu_ranking = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int menu_settings = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
